### ISSUE TITLE
🧐 <svg> elements are hard to see on light theme.

### ISSUE THREAD

**Issue by AustinCrouch296** [wavetro/testzone#1]
On the index.html page, the <svg> elements fill to white instead of black. 

Awesome job you've done so far, this repo and the site look really well organized! 
I look forward to seeing where you go with this. :)

**Comment by wavetro** [comment]
Thank you so much! I looked at my style sheets and it turns out I forgot to make a light theme in general, so I'll update the site to add that as soon as I have the free time to!
